copartnership/Controllers/ParnerFormsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using copartnership.Data;
using copartnership.Models;
using Microsoft.AspNetCore.Authorization;

namespace copartnership.Controllers
{
    [Authorize]
    public class ParnerFormsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ParnerFormsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ParnerForms
        public async Task<IActionResult> Index()
        {
            return _context.parnerForms != null ?
                        View(await _context.parnerForms.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.partnerOrders'  is null.");
        }

        // GET: ParnerForms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.parnerForms == null)
            {
                return NotFound();
            }

            var partnerOrder = await _context.parnerForms
                .FirstOrDefaultAsync(m => m.Id == id);
            if (partnerOrder == null)
            {
                return NotFound();
            }

            return View(partnerOrder);
        }

        // GET: ParnerForms/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ParnerForms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NationalId,PartnerType,Dept,PartnerDate,ParnerDuration,userid,StatusId")] ParnerForm parnerForm)
        {
            ModelState.Remove("userid");
            ModelState.Remove("StatusId");
            if (ModelState.IsValid)
            {
                _context.Add(parnerForm);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(parnerForm);
        }

        // GET: ParnerForms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.parnerForms == null)
            {
                return NotFound();
            }

            var parnerForm = await _context.parnerForms.FindAsync(id);
            if (parnerForm == null)
            {
                return NotFound();
            }
            return View(parnerForm);
        }

        // POST: ParnerForms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NationalId,PartnerType,Dept,PartnerDate,ParnerDuration,userid,StatusId")] ParnerForm parnerForm)
        {
            if (id != parnerForm.Id)
            {
                return NotFound();
            }
            ModelState.Remove("userid");

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(parnerForm);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ParnerFormExists(parnerForm.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(parnerForm);
        }

        // GET: ParnerForms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.parnerForms == null)
            {
                return NotFound();
            }

            var parnerForm = await _context.parnerForms
                .FirstOrDefaultAsync(m => m.Id == id);
            if (parnerForm == null)
            {
                return NotFound();
            }

            return View(parnerForm);
        }

        // POST: ParnerForms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.parnerForms == null)
            {
                return Problem("Entity set 'ApplicationDbContext.parnerForms'  is null.");
            }
            var parnerForm = await _context.parnerForms.FindAsync(id);
            if (parnerForm != null)
            {
                _context.parnerForms.Remove(parnerForm);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ParnerFormExists(int id)
        {
          return (_context.parnerForms?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

copartnership/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] شراكة</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/copartnership.styles.css" asp-append-version="true" />
</head>
@{
    string menuTextColor = "text-white";
}
<body>
    <div class="container-fluid " style="background:linear-gradient(to left, #28347d, #19767D)">
            <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm   box-shadow mb-3">
            <div class="container-fluid">
                <a id="icon" class="navbar-brand @menuTextColor" asp-area="" asp-controller="Home" asp-action="Index">شراكة</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link @menuTextColor" asp-area="" asp-controller="Home" asp-action="Index">الرئيسية</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link @menuTextColor" asp-area="" asp-controller="ParnerForms" asp-action="Create">إنشاء شراكة</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link @menuTextColor" asp-area="" asp-controller="ParnerForms" asp-action="ShowPartner">شراكاتي </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link @menuTextColor" asp-area="" asp-controller="Roles" asp-action="Index">ادارة الصلاحيات </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link @menuTextColor" asp-area="" asp-controller="Users" asp-action="Index">ادارة المستخدمين </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link @menuTextColor" asp-area="" asp-controller="Home" asp-action="Privacy">سياسة الخصوصية</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    </div>
    <div class="container @menuTextColor">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class=" footer text-muted" style="background:linear-gradient(to left, #28347d, #19767D)">
        <div class="container">
            &copy; 2022 - شراكة - <a asp-area="" asp-controller="Home" asp-action="Privacy" class="@menuTextColor text-decoration-none">سياسة الخصوصية</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>